// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "4c8b9694-4abb-4a98-96a8-a00bc1c9732c";

const char SSID[]               = "Mand2g";    // Network SSID (name)
const char PASS[]               = "Luciene.456";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "AtLj6ASShdVqIZWc0deZrRiAX";    // Secret device password

void onLedChange();

CloudColoredLight led;
CloudTemperatureSensor temperatura;
CloudIlluminance ldr;
int potenciometro;
bool sistema;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(led, READWRITE, ON_CHANGE, onLedChange);
  ArduinoCloud.addProperty(temperatura, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(ldr, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(potenciometro, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(sistema, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
